### PR TITLE
feat: allow user-path authentication

### PR DESCRIPTION
**Pull request by ainghazal**
minor fixes that were needed to allow user & pass authentication (for tunnelbear).

### CODE REVIEW

**Comment by ainghazal** [comment]
to be rebased on top of #29 - this one also adds tests for newTunnelInfoFromPushedOptions

**Comment by ainghazal** [comment]
ready for review!

**Review by bassosimone — APPROVED** [review]
🐳

**Comment by ainghazal** [comment]
thanks a lot for reviewing this! it's merged :)

**Pull request merged**
